name: Nightly Builds

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "__legacy__/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - ".github/workflow-files/**"
      - ".github/workflows/*"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "__legacy__/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - ".github/workflow-files/**"
      - ".github/workflows/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.mc-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: ${{ matrix.unsupported }}

    strategy:
      fail-fast: false
      matrix:
        mc-version: [1.17.1, 1.18.2, 1.19.2]
        unsupported: [false]

        include:
          - mc-version: 1.8.8
            unsupported: true

          - mc-version: 1.12.2
            unsupported: true

          - mc-version: 1.16.5
            unsupported: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: "17"
          cache: 'gradle'
      - name: Change target version to ${{ matrix.mc-version }}
        run: |
          bash .github/workflow-files/change-ver.sh "${{ matrix.mc-version }}"
      - name: Build with shadowJar
        run: bash ./gradlew --no-daemon shadowJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: Agent-${{ matrix.mc-version }}.jar
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/*.jar
          if-no-files-found: error
